name: Node.js CI

on:
  push:
    branches: 
      - main
      - ci/test
  pull_request:
    types: [opened, synchronize]

jobs:
  integration:
    runs-on: ubuntu-latest
    env:
      SST_STAGE: staging
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Format
        run: pnpm format

      - name: Lint
        run: pnpm lint
      
      - name: Install SST
        run: pnpm sst install

      - name: Start SST Tunnel
        run: |
          nohup pnpm sst tunnel > tunnel.log 2>&1 & sleep 5 

      - name: Deploy Staging environment
        run: pnpm sst deploy

      - name: Migrate Database
        run: pnpm run db push

      - name: Stop SST Tunnel
        run: |
          pkill -f "pnpm sst tunnel"
          
      - name: Test
        run: pnpm test
