name: Integration
env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SST_STAGE: staging
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        run: pnpm test
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Format
        run: pnpm format   
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm lint      
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: pnpm typecheck

  migrate_deploy_staging:
    runs-on: codebuild-todo-app-staging-${{ github.run_id }}-${{ github.run_attempt }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-migrate-deploy-staging

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Deploy Staging environment
        run: pnpm sst deploy

      - name: Migrate Database
        run: pnpm run db migrate

  end_to_end_testing:
      runs-on: ubuntu-latest
      needs: [migrate_deploy_staging]
      steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test E2E
        run: pnpm run test:e2e    
          
